// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: porsNode.proto

package types

import (
	context "context"
	types "code.corp.bcollie.net/omnilink/omnilink-base/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is used in exec itself
type PorsNodePower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Power   int64  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
}

func (x *PorsNodePower) Reset() {
	*x = PorsNodePower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorsNodePower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorsNodePower) ProtoMessage() {}

func (x *PorsNodePower) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorsNodePower.ProtoReflect.Descriptor instead.
func (*PorsNodePower) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{0}
}

func (x *PorsNodePower) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PorsNodePower) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

// Consensus send request
type ReqPorsNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *ReqPorsNodes) Reset() {
	*x = ReqPorsNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPorsNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPorsNodes) ProtoMessage() {}

func (x *ReqPorsNodes) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPorsNodes.ProtoReflect.Descriptor instead.
func (*ReqPorsNodes) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPorsNodes) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Exec response
type PorsNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*PorsNodePower `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *PorsNodes) Reset() {
	*x = PorsNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorsNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorsNodes) ProtoMessage() {}

func (x *PorsNodes) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorsNodes.ProtoReflect.Descriptor instead.
func (*PorsNodes) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{2}
}

func (x *PorsNodes) GetNodes() []*PorsNodePower {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PorsPowerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Power   int64       `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	Height  int64       `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Proof   *PowerProof `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *PorsPowerUpdate) Reset() {
	*x = PorsPowerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorsPowerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorsPowerUpdate) ProtoMessage() {}

func (x *PorsPowerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorsPowerUpdate.ProtoReflect.Descriptor instead.
func (*PorsPowerUpdate) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{3}
}

func (x *PorsPowerUpdate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PorsPowerUpdate) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PorsPowerUpdate) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PorsPowerUpdate) GetProof() *PowerProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type PowerProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PubkeyBytes   [][]byte `protobuf:"bytes,1,rep,name=pubkeyBytes,proto3" json:"pubkeyBytes,omitempty"`
	AggregatedSig []byte   `protobuf:"bytes,2,opt,name=aggregatedSig,proto3" json:"aggregatedSig,omitempty"`
}

func (x *PowerProof) Reset() {
	*x = PowerProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerProof) ProtoMessage() {}

func (x *PowerProof) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerProof.ProtoReflect.Descriptor instead.
func (*PowerProof) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{4}
}

func (x *PowerProof) GetPubkeyBytes() [][]byte {
	if x != nil {
		return x.PubkeyBytes
	}
	return nil
}

func (x *PowerProof) GetAggregatedSig() []byte {
	if x != nil {
		return x.AggregatedSig
	}
	return nil
}

type PorsExecAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*PorsExecAction_PowerUpdate
	//	*PorsExecAction_BlockInfo
	Value isPorsExecAction_Value `protobuf_oneof:"value"`
	Ty    int32                  `protobuf:"varint,100,opt,name=Ty,json=ty,proto3" json:"Ty,omitempty"`
}

func (x *PorsExecAction) Reset() {
	*x = PorsExecAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorsExecAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorsExecAction) ProtoMessage() {}

func (x *PorsExecAction) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorsExecAction.ProtoReflect.Descriptor instead.
func (*PorsExecAction) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{5}
}

func (m *PorsExecAction) GetValue() isPorsExecAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *PorsExecAction) GetPowerUpdate() *PorsPowerUpdate {
	if x, ok := x.GetValue().(*PorsExecAction_PowerUpdate); ok {
		return x.PowerUpdate
	}
	return nil
}

func (x *PorsExecAction) GetBlockInfo() *PorsBlockInfo {
	if x, ok := x.GetValue().(*PorsExecAction_BlockInfo); ok {
		return x.BlockInfo
	}
	return nil
}

func (x *PorsExecAction) GetTy() int32 {
	if x != nil {
		return x.Ty
	}
	return 0
}

type isPorsExecAction_Value interface {
	isPorsExecAction_Value()
}

type PorsExecAction_PowerUpdate struct {
	PowerUpdate *PorsPowerUpdate `protobuf:"bytes,1,opt,name=powerUpdate,proto3,oneof"`
}

type PorsExecAction_BlockInfo struct {
	BlockInfo *PorsBlockInfo `protobuf:"bytes,2,opt,name=blockInfo,proto3,oneof"`
}

func (*PorsExecAction_PowerUpdate) isPorsExecAction_Value() {}

func (*PorsExecAction_BlockInfo) isPorsExecAction_Value() {}

type ReqPorsBlockInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *ReqPorsBlockInfo) Reset() {
	*x = ReqPorsBlockInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPorsBlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPorsBlockInfo) ProtoMessage() {}

func (x *ReqPorsBlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPorsBlockInfo.ProtoReflect.Descriptor instead.
func (*ReqPorsBlockInfo) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{6}
}

func (x *ReqPorsBlockInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// This is from consensus
type PorsNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIP      string `protobuf:"bytes,1,opt,name=nodeIP,proto3" json:"nodeIP,omitempty"`
	NodeID      string `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Address     string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PubKey      string `protobuf:"bytes,4,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	VotingPower int64  `protobuf:"varint,5,opt,name=votingPower,proto3" json:"votingPower,omitempty"`
	Accum       int64  `protobuf:"varint,6,opt,name=accum,proto3" json:"accum,omitempty"`
}

func (x *PorsNodeInfo) Reset() {
	*x = PorsNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorsNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorsNodeInfo) ProtoMessage() {}

func (x *PorsNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorsNodeInfo.ProtoReflect.Descriptor instead.
func (*PorsNodeInfo) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{7}
}

func (x *PorsNodeInfo) GetNodeIP() string {
	if x != nil {
		return x.NodeIP
	}
	return ""
}

func (x *PorsNodeInfo) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *PorsNodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PorsNodeInfo) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *PorsNodeInfo) GetVotingPower() int64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *PorsNodeInfo) GetAccum() int64 {
	if x != nil {
		return x.Accum
	}
	return 0
}

type PorsNodeInfoSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*PorsNodeInfo `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *PorsNodeInfoSet) Reset() {
	*x = PorsNodeInfoSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_porsNode_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorsNodeInfoSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorsNodeInfoSet) ProtoMessage() {}

func (x *PorsNodeInfoSet) ProtoReflect() protoreflect.Message {
	mi := &file_porsNode_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorsNodeInfoSet.ProtoReflect.Descriptor instead.
func (*PorsNodeInfoSet) Descriptor() ([]byte, []int) {
	return file_porsNode_proto_rawDescGZIP(), []int{8}
}

func (x *PorsNodeInfoSet) GetNodes() []*PorsNodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_porsNode_proto protoreflect.FileDescriptor

var file_porsNode_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x70, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3f, 0x0a, 0x0d, 0x50, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x37, 0x0a, 0x09, 0x50, 0x6f,
	0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50,
	0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x50, 0x6f, 0x72, 0x73, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x27, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x54, 0x0a, 0x0a, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x67, 0x22, 0x9b,
	0x01, 0x0a, 0x0e, 0x50, 0x6f, 0x72, 0x73, 0x45, 0x78, 0x65, 0x63, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x3a, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50,
	0x6f, 0x72, 0x73, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00,
	0x52, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x72, 0x73, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x79, 0x18, 0x64, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x74, 0x79, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x50, 0x6f, 0x72, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x72,
	0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x50, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x76,
	0x6f, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x63,
	0x63, 0x75, 0x6d, 0x22, 0x3c, 0x0a, 0x0f, 0x50, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x53, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f,
	0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x32, 0x6f, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x49, 0x73, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x0d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x4e,
	0x69, 0x6c, 0x1a, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x72, 0x73, 0x49,
	0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0d, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x4e, 0x69, 0x6c, 0x1a, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x50, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x74,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_porsNode_proto_rawDescOnce sync.Once
	file_porsNode_proto_rawDescData = file_porsNode_proto_rawDesc
)

func file_porsNode_proto_rawDescGZIP() []byte {
	file_porsNode_proto_rawDescOnce.Do(func() {
		file_porsNode_proto_rawDescData = protoimpl.X.CompressGZIP(file_porsNode_proto_rawDescData)
	})
	return file_porsNode_proto_rawDescData
}

var file_porsNode_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_porsNode_proto_goTypes = []interface{}{
	(*PorsNodePower)(nil),    // 0: types.PorsNodePower
	(*ReqPorsNodes)(nil),     // 1: types.ReqPorsNodes
	(*PorsNodes)(nil),        // 2: types.PorsNodes
	(*PorsPowerUpdate)(nil),  // 3: types.PorsPowerUpdate
	(*PowerProof)(nil),       // 4: types.PowerProof
	(*PorsExecAction)(nil),   // 5: types.PorsExecAction
	(*ReqPorsBlockInfo)(nil), // 6: types.ReqPorsBlockInfo
	(*PorsNodeInfo)(nil),     // 7: types.PorsNodeInfo
	(*PorsNodeInfoSet)(nil),  // 8: types.PorsNodeInfoSet
	(*PorsBlockInfo)(nil),    // 9: types.PorsBlockInfo
	(*types.ReqNil)(nil),     // 10: types.ReqNil
	(*PorsIsHealthy)(nil),    // 11: types.PorsIsHealthy
}
var file_porsNode_proto_depIdxs = []int32{
	0,  // 0: types.PorsNodes.nodes:type_name -> types.PorsNodePower
	4,  // 1: types.PorsPowerUpdate.proof:type_name -> types.PowerProof
	3,  // 2: types.PorsExecAction.powerUpdate:type_name -> types.PorsPowerUpdate
	9,  // 3: types.PorsExecAction.blockInfo:type_name -> types.PorsBlockInfo
	7,  // 4: types.PorsNodeInfoSet.nodes:type_name -> types.PorsNodeInfo
	10, // 5: types.pors.IsSync:input_type -> types.ReqNil
	10, // 6: types.pors.GetNodeInfo:input_type -> types.ReqNil
	11, // 7: types.pors.IsSync:output_type -> types.PorsIsHealthy
	8,  // 8: types.pors.GetNodeInfo:output_type -> types.PorsNodeInfoSet
	7,  // [7:9] is the sub-list for method output_type
	5,  // [5:7] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_porsNode_proto_init() }
func file_porsNode_proto_init() {
	if File_porsNode_proto != nil {
		return
	}
	file_pors_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_porsNode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorsNodePower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPorsNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorsNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorsPowerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorsExecAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPorsBlockInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorsNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_porsNode_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorsNodeInfoSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_porsNode_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*PorsExecAction_PowerUpdate)(nil),
		(*PorsExecAction_BlockInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_porsNode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_porsNode_proto_goTypes,
		DependencyIndexes: file_porsNode_proto_depIdxs,
		MessageInfos:      file_porsNode_proto_msgTypes,
	}.Build()
	File_porsNode_proto = out.File
	file_porsNode_proto_rawDesc = nil
	file_porsNode_proto_goTypes = nil
	file_porsNode_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PorsClient is the client API for Pors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PorsClient interface {
	IsSync(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*PorsIsHealthy, error)
	GetNodeInfo(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*PorsNodeInfoSet, error)
}

type porsClient struct {
	cc grpc.ClientConnInterface
}

func NewPorsClient(cc grpc.ClientConnInterface) PorsClient {
	return &porsClient{cc}
}

func (c *porsClient) IsSync(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*PorsIsHealthy, error) {
	out := new(PorsIsHealthy)
	err := c.cc.Invoke(ctx, "/types.pors/IsSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *porsClient) GetNodeInfo(ctx context.Context, in *types.ReqNil, opts ...grpc.CallOption) (*PorsNodeInfoSet, error) {
	out := new(PorsNodeInfoSet)
	err := c.cc.Invoke(ctx, "/types.pors/GetNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PorsServer is the server API for Pors service.
type PorsServer interface {
	IsSync(context.Context, *types.ReqNil) (*PorsIsHealthy, error)
	GetNodeInfo(context.Context, *types.ReqNil) (*PorsNodeInfoSet, error)
}

// UnimplementedPorsServer can be embedded to have forward compatible implementations.
type UnimplementedPorsServer struct {
}

func (*UnimplementedPorsServer) IsSync(context.Context, *types.ReqNil) (*PorsIsHealthy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsSync not implemented")
}
func (*UnimplementedPorsServer) GetNodeInfo(context.Context, *types.ReqNil) (*PorsNodeInfoSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}

func RegisterPorsServer(s *grpc.Server, srv PorsServer) {
	s.RegisterService(&_Pors_serviceDesc, srv)
}

func _Pors_IsSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PorsServer).IsSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.pors/IsSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PorsServer).IsSync(ctx, req.(*types.ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pors_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PorsServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.pors/GetNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PorsServer).GetNodeInfo(ctx, req.(*types.ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pors_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.pors",
	HandlerType: (*PorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsSync",
			Handler:    _Pors_IsSync_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _Pors_GetNodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "porsNode.proto",
}
