syntax = "proto3";

import "blockchain.proto";

package types;
option go_package = "../types";

message PorsBlockID {
    bytes hash = 1;
}

message PorsBitArray {
    int32    bits         = 1;
    repeated uint64 elems = 2;
}

message PorsVote {
    bytes       validatorAddress = 1;
    int32       validatorIndex   = 2;
    int64       height           = 3;
    int32       round            = 4;
    int64       timestamp        = 5;
    uint32      type             = 6;
    PorsBlockID blockID          = 7;
    bytes       signature        = 8;
    bool        useAggSig        = 9;
}

message PorsCommit {
    PorsBlockID       blockID    = 1;
    repeated PorsVote prevotes   = 2;
    repeated PorsVote precommits = 3;
    PorsAggVote       aggVote    = 4;
    uint32            voteType   = 5;
}

message PorsBlockInfo {
    PorsState    state    = 1;
    PorsProposal proposal = 2;
    PorsBlock    block    = 3;
}

message PorsBlockSize {
    int32 maxBytes = 1;
    int32 maxTxs   = 2;
    int64 maxGas   = 3;
}

message PorsTxSize {
    int32 maxBytes = 1;
    int64 maxGas   = 2;
}

message PorsBlockGossip {
    int32 blockPartSizeBytes = 1;
}

message PorsEvidenceParams {
    int64 maxAge = 1;
}
message PorsConsensusParams {
    PorsBlockSize      blockSize      = 1;
    PorsTxSize         txSize         = 2;
    PorsBlockGossip    blockGossip    = 3;
    PorsEvidenceParams evidenceParams = 4;
}

message PorsValidator {
    string address     = 1;
    string pubKey      = 2;
    int64  votingPower = 3;
    int64  accum       = 4;
}

message PorsValidatorSet {
    repeated PorsValidator validators = 1;
    PorsValidator          proposer   = 2;
}

message PorsState {
    string              chainID                          = 1;
    int64               lastBlockHeight                  = 2;
    int64               lastBlockTotalTx                 = 3;
    PorsBlockID         lastBlockID                      = 4;
    int64               lastBlockTime                    = 5;
    PorsValidatorSet    validators                       = 6;
    PorsValidatorSet    lastValidators                   = 7;
    int64               lastHeightValidatorsChanged      = 8;
    PorsConsensusParams consensusParams                  = 9;
    int64               lastHeightConsensusParamsChanged = 10;
    bytes               lastResultsHash                  = 11;
    bytes               appHash                          = 12;
    int64               sequence                         = 13;
    int64               lastSequence                     = 14;
    int64               lastCommitRound                  = 15;
}

message PorsBlockHeader {
    string      chainID         = 1;
    int64       height          = 2;
    int64       round           = 3;
    int64       time            = 4;
    int64       numTxs          = 5;
    PorsBlockID lastBlockID     = 6;
    int64       totalTxs        = 7;
    bytes       lastCommitHash  = 8;
    bytes       validatorsHash  = 9;
    bytes       consensusHash   = 10;
    bytes       appHash         = 11;
    bytes       lastResultsHash = 12;
    bytes       proposerAddr    = 13;
    int64       sequence        = 14;
    int64       lastSequence    = 15;
}

message PorsBlock {
    PorsBlockHeader header     = 1;
    Block           data       = 2;
    PorsCommit      lastCommit = 4;
}

message PorsProposal {
    int64       height     = 1;
    int32       round      = 2;
    int64       timestamp  = 3;
    int32       POLRound   = 4;
    PorsBlockID POLBlockID = 5;
    bytes       signature  = 6;
    bytes       blockhash  = 7;
    int64       sequence   = 8;
}

message PorsNewRoundStepMsg {
    int64 height                = 1;
    int32 round                 = 2;
    int32 step                  = 3;
    int32 secondsSinceStartTime = 4;
    int32 lastCommitRound       = 5;
}

message PorsValidBlockMsg {
    int64 height    = 1;
    int32 round     = 2;
    bytes blockhash = 3;
    bool  isCommit  = 4;
}

message PorsProposalPOLMsg {
    int64        height           = 1;
    int32        proposalPOLRound = 2;
    PorsBitArray proposalPOL      = 3;
}

message PorsHasVoteMsg {
    int64 height = 1;
    int32 round  = 2;
    int32 type   = 3;
    int32 index  = 4;
}

message PorsVoteSetMaj23Msg {
    int64       height  = 1;
    int32       round   = 2;
    int32       type    = 3;
    PorsBlockID blockID = 4;
}

message PorsVoteSetBitsMsg {
    int64        height  = 1;
    int32        round   = 2;
    int32        type    = 3;
    PorsBlockID  blockID = 4;
    PorsBitArray votes   = 5;
}

message PorsHeartbeat {
    bytes validatorAddress = 1;
    int32 validatorIndex   = 2;
    int64 height           = 3;
    int32 round            = 4;
    int32 sequence         = 5;
    bytes signature        = 6;
}

message PorsIsHealthy {
    bool isHealthy = 1;
}

message PorsAggVote {
    bytes        validatorAddress = 1;
    PorsBitArray validatorArray   = 2;
    int64        height           = 3;
    int32        round            = 4;
    int64        timestamp        = 5;
    uint32       type             = 6;
    PorsBlockID  blockID          = 7;
    bytes        signature        = 8;
}
