// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: transferAction.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetsTransferToExecOmnilink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cointoken string `protobuf:"bytes,1,opt,name=cointoken,proto3" json:"cointoken,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Note      []byte `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	ExecName  string `protobuf:"bytes,4,opt,name=execName,proto3" json:"execName,omitempty"`
	To        string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *AssetsTransferToExecOmnilink) Reset() {
	*x = AssetsTransferToExecOmnilink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferAction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetsTransferToExecOmnilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsTransferToExecOmnilink) ProtoMessage() {}

func (x *AssetsTransferToExecOmnilink) ProtoReflect() protoreflect.Message {
	mi := &file_transferAction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsTransferToExecOmnilink.ProtoReflect.Descriptor instead.
func (*AssetsTransferToExecOmnilink) Descriptor() ([]byte, []int) {
	return file_transferAction_proto_rawDescGZIP(), []int{0}
}

func (x *AssetsTransferToExecOmnilink) GetCointoken() string {
	if x != nil {
		return x.Cointoken
	}
	return ""
}

func (x *AssetsTransferToExecOmnilink) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AssetsTransferToExecOmnilink) GetNote() []byte {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *AssetsTransferToExecOmnilink) GetExecName() string {
	if x != nil {
		return x.ExecName
	}
	return ""
}

func (x *AssetsTransferToExecOmnilink) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type AssetsTransferOmnilink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cointoken string `protobuf:"bytes,1,opt,name=cointoken,proto3" json:"cointoken,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Note      []byte `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	To        string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *AssetsTransferOmnilink) Reset() {
	*x = AssetsTransferOmnilink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferAction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetsTransferOmnilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsTransferOmnilink) ProtoMessage() {}

func (x *AssetsTransferOmnilink) ProtoReflect() protoreflect.Message {
	mi := &file_transferAction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsTransferOmnilink.ProtoReflect.Descriptor instead.
func (*AssetsTransferOmnilink) Descriptor() ([]byte, []int) {
	return file_transferAction_proto_rawDescGZIP(), []int{1}
}

func (x *AssetsTransferOmnilink) GetCointoken() string {
	if x != nil {
		return x.Cointoken
	}
	return ""
}

func (x *AssetsTransferOmnilink) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AssetsTransferOmnilink) GetNote() []byte {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *AssetsTransferOmnilink) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type CoinsActionOmnilink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*CoinsActionOmnilink_Transfer
	//	*CoinsActionOmnilink_TransferToExec
	Value isCoinsActionOmnilink_Value `protobuf_oneof:"value"`
	Ty    int32                       `protobuf:"varint,3,opt,name=ty,proto3" json:"ty,omitempty"`
}

func (x *CoinsActionOmnilink) Reset() {
	*x = CoinsActionOmnilink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferAction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinsActionOmnilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinsActionOmnilink) ProtoMessage() {}

func (x *CoinsActionOmnilink) ProtoReflect() protoreflect.Message {
	mi := &file_transferAction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinsActionOmnilink.ProtoReflect.Descriptor instead.
func (*CoinsActionOmnilink) Descriptor() ([]byte, []int) {
	return file_transferAction_proto_rawDescGZIP(), []int{2}
}

func (m *CoinsActionOmnilink) GetValue() isCoinsActionOmnilink_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CoinsActionOmnilink) GetTransfer() *AssetsTransferOmnilink {
	if x, ok := x.GetValue().(*CoinsActionOmnilink_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (x *CoinsActionOmnilink) GetTransferToExec() *AssetsTransferToExecOmnilink {
	if x, ok := x.GetValue().(*CoinsActionOmnilink_TransferToExec); ok {
		return x.TransferToExec
	}
	return nil
}

func (x *CoinsActionOmnilink) GetTy() int32 {
	if x != nil {
		return x.Ty
	}
	return 0
}

type isCoinsActionOmnilink_Value interface {
	isCoinsActionOmnilink_Value()
}

type CoinsActionOmnilink_Transfer struct {
	Transfer *AssetsTransferOmnilink `protobuf:"bytes,1,opt,name=transfer,proto3,oneof"`
}

type CoinsActionOmnilink_TransferToExec struct {
	TransferToExec *AssetsTransferToExecOmnilink `protobuf:"bytes,2,opt,name=transferToExec,proto3,oneof"`
}

func (*CoinsActionOmnilink_Transfer) isCoinsActionOmnilink_Value() {}

func (*CoinsActionOmnilink_TransferToExec) isCoinsActionOmnilink_Value() {}

// 创建/调用合约的请求结构
type EVMAction4Omnilink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 转账金额
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// 消耗限制，默认为Transaction.Fee
	GasLimit uint64 `protobuf:"varint,2,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	// gas价格，默认为1
	GasPrice uint32 `protobuf:"varint,3,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// 合约数据
	Code []byte `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// 交易参数
	Para []byte `protobuf:"bytes,5,opt,name=para,proto3" json:"para,omitempty"`
	// 合约别名，方便识别
	Alias string `protobuf:"bytes,6,opt,name=alias,proto3" json:"alias,omitempty"`
	// 交易备注
	Note string `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	// 调用合约地址
	ContractAddr string `protobuf:"bytes,8,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
}

func (x *EVMAction4Omnilink) Reset() {
	*x = EVMAction4Omnilink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferAction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EVMAction4Omnilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVMAction4Omnilink) ProtoMessage() {}

func (x *EVMAction4Omnilink) ProtoReflect() protoreflect.Message {
	mi := &file_transferAction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVMAction4Omnilink.ProtoReflect.Descriptor instead.
func (*EVMAction4Omnilink) Descriptor() ([]byte, []int) {
	return file_transferAction_proto_rawDescGZIP(), []int{3}
}

func (x *EVMAction4Omnilink) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EVMAction4Omnilink) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *EVMAction4Omnilink) GetGasPrice() uint32 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *EVMAction4Omnilink) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *EVMAction4Omnilink) GetPara() []byte {
	if x != nil {
		return x.Para
	}
	return nil
}

func (x *EVMAction4Omnilink) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *EVMAction4Omnilink) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *EVMAction4Omnilink) GetContractAddr() string {
	if x != nil {
		return x.ContractAddr
	}
	return ""
}

type TransactionOmnilink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Execer    []byte             `protobuf:"bytes,1,opt,name=execer,proto3" json:"execer,omitempty"`
	Payload   []byte             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature *SignatureOmnilink `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Fee       int64              `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Expire    int64              `protobuf:"varint,5,opt,name=expire,proto3" json:"expire,omitempty"`
	// 随机ID，可以防止payload 相同的时候，交易重复
	Nonce int64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// 对方地址，如果没有对方地址，可以为空
	To         string `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	GroupCount int32  `protobuf:"varint,8,opt,name=groupCount,proto3" json:"groupCount,omitempty"`
	Header     []byte `protobuf:"bytes,9,opt,name=header,proto3" json:"header,omitempty"`
	Next       []byte `protobuf:"bytes,10,opt,name=next,proto3" json:"next,omitempty"`
	ChainID    int32  `protobuf:"varint,11,opt,name=chainID,proto3" json:"chainID,omitempty"`
}

func (x *TransactionOmnilink) Reset() {
	*x = TransactionOmnilink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferAction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionOmnilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOmnilink) ProtoMessage() {}

func (x *TransactionOmnilink) ProtoReflect() protoreflect.Message {
	mi := &file_transferAction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOmnilink.ProtoReflect.Descriptor instead.
func (*TransactionOmnilink) Descriptor() ([]byte, []int) {
	return file_transferAction_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionOmnilink) GetExecer() []byte {
	if x != nil {
		return x.Execer
	}
	return nil
}

func (x *TransactionOmnilink) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransactionOmnilink) GetSignature() *SignatureOmnilink {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TransactionOmnilink) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionOmnilink) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *TransactionOmnilink) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionOmnilink) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionOmnilink) GetGroupCount() int32 {
	if x != nil {
		return x.GroupCount
	}
	return 0
}

func (x *TransactionOmnilink) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TransactionOmnilink) GetNext() []byte {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *TransactionOmnilink) GetChainID() int32 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

type SignatureOmnilink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ty     int32  `protobuf:"varint,1,opt,name=ty,proto3" json:"ty,omitempty"`
	Pubkey []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// 当ty为5时，格式应该用RingSignature去解析
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignatureOmnilink) Reset() {
	*x = SignatureOmnilink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transferAction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureOmnilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureOmnilink) ProtoMessage() {}

func (x *SignatureOmnilink) ProtoReflect() protoreflect.Message {
	mi := &file_transferAction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureOmnilink.ProtoReflect.Descriptor instead.
func (*SignatureOmnilink) Descriptor() ([]byte, []int) {
	return file_transferAction_proto_rawDescGZIP(), []int{5}
}

func (x *SignatureOmnilink) GetTy() int32 {
	if x != nil {
		return x.Ty
	}
	return 0
}

func (x *SignatureOmnilink) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SignatureOmnilink) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_transferAction_proto protoreflect.FileDescriptor

var file_transferAction_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x94, 0x01,
	0x0a, 0x1c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x54, 0x6f, 0x45, 0x78, 0x65, 0x63, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x16, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x69,
	0x6e, 0x73, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b,
	0x12, 0x3b, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e,
	0x6b, 0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x4d, 0x0a,
	0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x6f, 0x45, 0x78, 0x65, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x6f, 0x45, 0x78,
	0x65, 0x63, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x0e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x6f, 0x45, 0x78, 0x65, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x79, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xda, 0x01, 0x0a, 0x12, 0x45, 0x56, 0x4d, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x34, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x61, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x70, 0x61, 0x72, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x22, 0xb5, 0x02, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78,
	0x65, 0x63, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x78, 0x65, 0x63,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x36, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x4f, 0x5a, 0x4d, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x63, 0x6f,
	0x72, 0x70, 0x2e, 0x62, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x6f,
	0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x6f, 0x6d, 0x6e, 0x69, 0x6c, 0x69, 0x6e, 0x6b,
	0x2d, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x65, 0x74, 0x68,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transferAction_proto_rawDescOnce sync.Once
	file_transferAction_proto_rawDescData = file_transferAction_proto_rawDesc
)

func file_transferAction_proto_rawDescGZIP() []byte {
	file_transferAction_proto_rawDescOnce.Do(func() {
		file_transferAction_proto_rawDescData = protoimpl.X.CompressGZIP(file_transferAction_proto_rawDescData)
	})
	return file_transferAction_proto_rawDescData
}

var file_transferAction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_transferAction_proto_goTypes = []interface{}{
	(*AssetsTransferToExecOmnilink)(nil), // 0: types.AssetsTransferToExecOmnilink
	(*AssetsTransferOmnilink)(nil),       // 1: types.AssetsTransferOmnilink
	(*CoinsActionOmnilink)(nil),          // 2: types.CoinsActionOmnilink
	(*EVMAction4Omnilink)(nil),           // 3: types.EVMAction4Omnilink
	(*TransactionOmnilink)(nil),          // 4: types.TransactionOmnilink
	(*SignatureOmnilink)(nil),            // 5: types.SignatureOmnilink
}
var file_transferAction_proto_depIdxs = []int32{
	1, // 0: types.CoinsActionOmnilink.transfer:type_name -> types.AssetsTransferOmnilink
	0, // 1: types.CoinsActionOmnilink.transferToExec:type_name -> types.AssetsTransferToExecOmnilink
	5, // 2: types.TransactionOmnilink.signature:type_name -> types.SignatureOmnilink
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transferAction_proto_init() }
func file_transferAction_proto_init() {
	if File_transferAction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transferAction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetsTransferToExecOmnilink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transferAction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetsTransferOmnilink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transferAction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinsActionOmnilink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transferAction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EVMAction4Omnilink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transferAction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionOmnilink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transferAction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignatureOmnilink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_transferAction_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CoinsActionOmnilink_Transfer)(nil),
		(*CoinsActionOmnilink_TransferToExec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transferAction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transferAction_proto_goTypes,
		DependencyIndexes: file_transferAction_proto_depIdxs,
		MessageInfos:      file_transferAction_proto_msgTypes,
	}.Build()
	File_transferAction_proto = out.File
	file_transferAction_proto_rawDesc = nil
	file_transferAction_proto_goTypes = nil
	file_transferAction_proto_depIdxs = nil
}
